# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vgacons.xdc

# Block Designs: bd/vgademo/vgademo.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vgademo || ORIG_REF_NAME==vgademo}]

# IP: bd/vgademo/ip/vgademo_processing_system7_0_0/vgademo_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vgademo_processing_system7_0_0 || ORIG_REF_NAME==vgademo_processing_system7_0_0}]

# IP: bd/vgademo/ip/vgademo_axi_vdma_0_0/vgademo_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vgademo_axi_vdma_0_0 || ORIG_REF_NAME==vgademo_axi_vdma_0_0}]

# IP: bd/vgademo/ip/vgademo_axi_mem_intercon_0/vgademo_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vgademo_axi_mem_intercon_0 || ORIG_REF_NAME==vgademo_axi_mem_intercon_0}]

# IP: bd/vgademo/ip/vgademo_processing_system7_0_axi_periph_0/vgademo_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vgademo_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==vgademo_processing_system7_0_axi_periph_0}]

# IP: bd/vgademo/ip/vgademo_axi_dispctrl_0_0/vgademo_axi_dispctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vgademo_axi_dispctrl_0_0 || ORIG_REF_NAME==vgademo_axi_dispctrl_0_0}]

# IP: bd/vgademo/ip/vgademo_xbar_0/vgademo_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vgademo_xbar_0 || ORIG_REF_NAME==vgademo_xbar_0}]

# IP: bd/vgademo/ip/vgademo_xlconstant_0_0/vgademo_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vgademo_xlconstant_0_0 || ORIG_REF_NAME==vgademo_xlconstant_0_0}]

# IP: bd/vgademo/ip/vgademo_auto_pc_0/vgademo_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vgademo_auto_pc_0 || ORIG_REF_NAME==vgademo_auto_pc_0}]

# IP: bd/vgademo/ip/vgademo_auto_pc_1/vgademo_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vgademo_auto_pc_1 || ORIG_REF_NAME==vgademo_auto_pc_1}]

# XDC: bd/vgademo/ip/vgademo_processing_system7_0_0/vgademo_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vgademo_processing_system7_0_0 || ORIG_REF_NAME==vgademo_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/vgademo/ip/vgademo_axi_vdma_0_0/vgademo_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vgademo_axi_vdma_0_0 || ORIG_REF_NAME==vgademo_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/vgademo/ip/vgademo_axi_vdma_0_0/vgademo_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vgademo_axi_vdma_0_0 || ORIG_REF_NAME==vgademo_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/vgademo/ip/vgademo_axi_vdma_0_0/vgademo_axi_vdma_0_0_ooc.xdc

# XDC: bd/vgademo/ip/vgademo_xbar_0/vgademo_xbar_0_ooc.xdc

# XDC: bd/vgademo/ip/vgademo_auto_pc_0/vgademo_auto_pc_0_ooc.xdc

# XDC: bd/vgademo/ip/vgademo_auto_pc_1/vgademo_auto_pc_1_ooc.xdc

# XDC: bd/vgademo/vgademo_ooc.xdc
