# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Study/Soc/SOC/labs/lab10/lab10VGA2/lab10VGA2.cache/wt [current_project]
set_property parent.project_path D:/Study/Soc/SOC/labs/lab10/lab10VGA2/lab10VGA2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths d:/Study/Soc/SOC/labs/lab10/zybo_base_system [current_project]
add_files D:/Study/Soc/SOC/labs/lab10/lab10VGA2/lab10VGA2.srcs/sources_1/bd/vgademo/vgademo.bd
set_property used_in_implementation false [get_files -all d:/Study/Soc/SOC/labs/lab10/lab10VGA2/lab10VGA2.srcs/sources_1/bd/vgademo/ip/vgademo_processing_system7_0_0/vgademo_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Study/Soc/SOC/labs/lab10/lab10VGA2/lab10VGA2.srcs/sources_1/bd/vgademo/ip/vgademo_axi_vdma_0_0/vgademo_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Study/Soc/SOC/labs/lab10/lab10VGA2/lab10VGA2.srcs/sources_1/bd/vgademo/ip/vgademo_axi_vdma_0_0/vgademo_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Study/Soc/SOC/labs/lab10/lab10VGA2/lab10VGA2.srcs/sources_1/bd/vgademo/ip/vgademo_axi_vdma_0_0/vgademo_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Study/Soc/SOC/labs/lab10/lab10VGA2/lab10VGA2.srcs/sources_1/bd/vgademo/ip/vgademo_xbar_0/vgademo_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Study/Soc/SOC/labs/lab10/lab10VGA2/lab10VGA2.srcs/sources_1/bd/vgademo/ip/vgademo_auto_pc_0/vgademo_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Study/Soc/SOC/labs/lab10/lab10VGA2/lab10VGA2.srcs/sources_1/bd/vgademo/ip/vgademo_auto_pc_1/vgademo_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Study/Soc/SOC/labs/lab10/lab10VGA2/lab10VGA2.srcs/sources_1/bd/vgademo/vgademo_ooc.xdc]
set_property is_locked true [get_files D:/Study/Soc/SOC/labs/lab10/lab10VGA2/lab10VGA2.srcs/sources_1/bd/vgademo/vgademo.bd]

read_verilog -library xil_defaultlib D:/Study/Soc/SOC/labs/lab10/lab10VGA2/lab10VGA2.srcs/sources_1/bd/vgademo/hdl/vgademo_wrapper.v
read_xdc D:/Study/Soc/SOC/labs/lab10/lab10VGA2/lab10VGA2.srcs/constrs_1/new/vgacons.xdc
set_property used_in_implementation false [get_files D:/Study/Soc/SOC/labs/lab10/lab10VGA2/lab10VGA2.srcs/constrs_1/new/vgacons.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top vgademo_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef vgademo_wrapper.dcp
catch { report_utilization -file vgademo_wrapper_utilization_synth.rpt -pb vgademo_wrapper_utilization_synth.pb }
